// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimationControlPanel: typeof import('./src/components/ControlPanel/AnimationControlPanel.vue')['default']
    AnimationSettingModal: typeof import('./src/components/ControlPanel/AnimationSettingModal.vue')['default']
    Area: typeof import('./src/components/Editor/Area.vue')['default']
    AttrControlPanel: typeof import('./src/components/ControlPanel/AttrControlPanel.vue')['default']
    ComponentList: typeof import('./src/components/ComponentList/ComponentList.vue')['default']
    ComponentWrapper: typeof import('./src/components/Editor/Preview/ComponentWrapper.vue')['default']
    ContextMenu: typeof import('./src/components/Editor/ContextMenu.vue')['default']
    Editor: typeof import('./src/components/Editor/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    EventControlPanel: typeof import('./src/components/ControlPanel/EventControlPanel.vue')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    MarkLine: typeof import('./src/components/Editor/MarkLine.vue')['default']
    Modal: typeof import('./src/components/ControlPanel/Modal.vue')['default']
    Preview: typeof import('./src/components/Editor/Preview/Preview.vue')['default']
    RealtimeComponentList: typeof import('./src/components/ComponentList/RealtimeComponentList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shape: typeof import('./src/components/Editor/Shape.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
